"""Generate deploy/db-init/*.sql from the development database.

Postgres runs these files once, when the pg_data volume is created empty
on a new client machine. Re-run this script whenever the schema changes.

    python deploy/make_db_init.py            # uses DB_* env vars / config.py

Output:
  01_schema.sql  every table, no data            (pg_dump --schema-only)
  02_seed.sql    starter configuration only:
                   Info_db        (daily counter / dates reset)
                   users          (superadmin only - no developer accounts)
                   Data           (PLC tag table - re-upload per site if different)
                   RecipeTagName  (recipe tag table)
                   MaterialData   (materials, TotalExtracted reset to 0)
                 No production history (plc_data, Batches) and no recipes.
"""
import glob
import os
import shutil
import subprocess
import sys

import psycopg2

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from config.config import DB_CONFIG  # noqa: E402

OUT_DIR = os.path.join(ROOT, "deploy", "db-init")


def find_pg_dump():
    found = shutil.which("pg_dump")
    if found:
        return found
    candidates = sorted(glob.glob(r"C:\Program Files\PostgreSQL\*\bin\pg_dump.exe"))
    if candidates:
        return candidates[-1]
    sys.exit("pg_dump not found - install the PostgreSQL client tools or add them to PATH")


def write_schema():
    env = dict(os.environ, PGPASSWORD=str(DB_CONFIG["password"]))
    schema = subprocess.run(
        [find_pg_dump(), "-h", DB_CONFIG["host"], "-p", str(DB_CONFIG["port"]),
         "-U", DB_CONFIG["user"], "--schema-only", "--no-owner", "--no-privileges",
         DB_CONFIG["dbname"]],
        env=env, capture_output=True, text=True, check=True,
    ).stdout
    # pg_dump 17+ emits psql-only \restrict lines; initdb runs files with psql, which is fine,
    # but keep the file readable by any client by dropping them.
    schema = "\n".join(l for l in schema.splitlines() if not l.startswith(("\\restrict", "\\unrestrict")))
    with open(os.path.join(OUT_DIR, "01_schema.sql"), "w", encoding="utf-8", newline="\n") as f:
        f.write(schema + "\n")


def inserts(cur, table, where="", overrides=None, blank_info=()):
    """INSERT statements for a table; overrides = {column: value} applied to every row,
    blank_info = Info_db "Particulars" whose "Info" is emptied."""
    cur.execute(f'SELECT * FROM "{table}" {where}')
    cols = [d[0] for d in cur.description]
    col_sql = ", ".join(f'"{c}"' for c in cols)
    lines = [f"-- {table}"]
    for row in cur.fetchall():
        row = list(row)
        for col, value in (overrides or {}).items():
            row[cols.index(col)] = value
        if blank_info and row[cols.index("Particulars")] in blank_info:
            row[cols.index("Info")] = ""
        values = cur.mogrify(", ".join(["%s"] * len(cols)), row).decode()
        lines.append(f'INSERT INTO "{table}" ({col_sql}) VALUES ({values});')
    return "\n".join(lines) + "\n"


def write_seed():
    conn = psycopg2.connect(host=DB_CONFIG["host"], port=DB_CONFIG["port"], dbname=DB_CONFIG["dbname"],
                            user=DB_CONFIG["user"], password=DB_CONFIG["password"])
    try:
        cur = conn.cursor()
        parts = [
            "-- Starter configuration for a new site. Generated by deploy/make_db_init.py\n",
            # Licence rows are blanked: every site activates with its own key
            inserts(cur, "Info_db", "WHERE \"Particulars\" NOT IN ('Batch_no', 'Last_Date', 'Licence_Last_Seen')",
                    blank_info=("Activation_Key", "Software_sold_date")),
            "INSERT INTO \"Info_db\" (\"Id\", \"Particulars\", \"Info\")\n"
            "SELECT COALESCE(MAX(\"Id\"), 0) + 1, 'Last_Date', '' FROM \"Info_db\";\n",
            inserts(cur, "users", "WHERE role = 'superadmin'", {"last_login": None}),
            inserts(cur, "Data"),
            inserts(cur, "RecipeTagName"),
            inserts(cur, "MaterialData", overrides={"TotalExtracted": "0"}),
        ]
        # Keep SERIAL/IDENTITY sequences ahead of the seeded ids
        cur.execute("""
            SELECT table_name, column_name, pg_get_serial_sequence(format('%I', table_name), column_name)
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND pg_get_serial_sequence(format('%I', table_name), column_name) IS NOT NULL
        """)
        for table, column, seq in cur.fetchall():
            parts.append(
                f"SELECT setval('{seq}', COALESCE((SELECT MAX(\"{column}\") FROM \"{table}\"), 0) + 1, false);\n")
    finally:
        conn.close()

    with open(os.path.join(OUT_DIR, "02_seed.sql"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(parts))


if __name__ == "__main__":
    os.makedirs(OUT_DIR, exist_ok=True)
    write_schema()
    write_seed()
    print(f"Wrote {OUT_DIR}\\01_schema.sql and 02_seed.sql")
